imported 20060531 current

diff --git a/src/etc/rc.d/named b/src/etc/rc.d/named
--- a/src/etc/rc.d/named
+++ b/src/etc/rc.d/named
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: named,v 1.14 2004/08/13 18:08:03 mycroft Exp $
+# $NetBSD: named,v 1.18 2005/11/29 21:07:25 christos Exp $
 #
 
 # PROVIDE: named
@@ -17,6 +17,44 @@ pidfile="/var/run/${name}.pid"
 start_precmd="named_precmd"
 extra_commands="reload"
 required_dirs="$named_chrootdir"	# if it is set, it must exist
+
+named_migrate()
+{
+	local src=$1
+	local dst=$2$1
+	echo "Migrating $src to $dst"
+(
+	diff=false
+	cd $src
+	for f in $(find . -type f)
+	do
+		f=${f##./}
+		case $f in
+		*/*)
+			d=$dst$(dirname $f)
+			;;
+		*)	d=$dst
+			;;
+		esac
+		mkdir -p $d
+		if [ -r "$dst/$f" ]
+		then
+			if ! cmp $f $dst/$f; then
+				diff=true
+			fi
+		else
+			cp -p $f $dst/$f
+		fi
+	done
+	if $diff; then
+		echo "Cannot complete migration because files are different"
+		echo "Run 'diff -r $src $dst' resolve the differences"
+	else
+		rm -fr $src
+		ln -s $dst $src
+	fi
+)
+}
 
 named_precmd()
 {
@@ -58,11 +96,25 @@ named_precmd()
 		fi
 	done
 
+	if [ ! -h /etc/namedb ]; then
+		named_migrate /etc/namedb ${named_chrootdir}
+	fi
+	if [ \( -r /etc/named.conf \) -a \( ! -h /etc/named.conf \) -a \
+	     \( ! -r ${named_chrootdir}/etc/named.conf \) ]
+	then
+		mv /etc/named.conf ${named_chrootdir}/etc/named.conf
+		ln -s ${named_chrootdir}/etc/named.conf /etc/named.conf
+	fi
+	if [ \( ! -r ${named_chrootdir}/etc/named.conf \) -a \
+	    \( -r ${named_chrootdir}/etc/namedb/named.conf \) ]; then
+		ln -s namedb/named.conf ${named_chrootdir}/etc
+	fi
+
 	if [ -f /etc/localtime ]; then
 		cmp -s /etc/localtime "${named_chrootdir}/etc/localtime" || \
 		    cp -p /etc/localtime "${named_chrootdir}/etc/localtime"
 	fi
-	ln -fs "${named_chrootdir}/var/run/named.pid" /var/run/named.pid
+	ln -fs "${named_chrootdir}${pidfile}" ${pidfile}
 
 	#	Change run_rc_commands()'s internal copy of $named_flags
 	#
